---
title: "Comparative Analysis"
author: ""
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(plotly)
library(knitr)
```

```{r include=FALSE}

## FUNCTIONS
rowVars <- function(x, ...) {
  rowSums((x - rowMeans(x, ...))^2, ...)/(dim(x)[2] - 1)
}

meansFromTo <- function(datafr, from, to, days_simulated) {
  means <- list()
  for (i in 2:days_simulated) {
    means[[i]] <- unlist(mean(datafr[datafr$time <= to & datafr$time >= from,][[paste("D", i, sep="")]]))
  }
  
  return(unlist(means))
}

varsFromTo <- function(datafr, from, to, days_simulated) {
  vars <- list()
  for (i in 2:days_simulated) {
    vars[[i]] <- unlist(var(datafr[datafr$time <= to & datafr$time >= from,][[paste("D", i, sep="")]]))
  }
  
  return(unlist(vars))
}

meanDiffConfInt <- function(a, b, from, to, level) {
  means_a = meansFromTo(a, from, to, days_simulated)
  means_b = meansFromTo(b, from, to, days_simulated)
  
  differences = means_a - means_b
  diff_var = var(differences)
  
  n = length(differences)
  grandmean = mean(differences);
  grandvariance = diff_var/n
  
  half_length = qt(1-level, df=n-1) * sqrt(grandvariance)
  
  return(c(grandmean - half_length, grandmean + half_length))
}

confInt <- function(means, variances, alpha) {
  n = length(means)
  grandmean = mean(means);
  grandvariance = mean(variances)/n
  
  half_length = qt(1-alpha, df=n-1) * sqrt(grandvariance)
  
  return(c(grandmean - half_length, grandmean + half_length))
}

confIntTable <- function(datafr, title) {
  
  means_7_9 = meansFromTo(datafr, 7, 9, days_simulated)
  vars_7_9 = varsFromTo(datafr, 7, 9, days_simulated)
  
  means_17_19 = meansFromTo(datafr, 17, 19, days_simulated)
  vars_17_19 = varsFromTo(datafr, 17, 19, days_simulated)
  
  cidf_7_9 = confInt(means_7_9, vars_7_9, 0.05)
  cidf_17_19 = confInt(means_17_19, vars_17_19, 0.05)
  
  cidf_7_9_09 = confInt(means_7_9, vars_7_9, 0.1)
  cidf_17_19_09 = confInt(means_17_19, vars_17_19, 0.1)
  
  cidf <- data.frame(
    Time_Interval=c("7am - 9am", "17pm - 19pm"), 
    Mean=c(mean(means_7_9), mean(means_17_19)),
    Variance=c(mean(vars_7_9), mean(vars_17_19)),
    VarianceOfMeans=c(var(means_7_9), var(means_17_19)),
    ConfIntLower0.95=c(cidf_7_9[1], cidf_17_19[1]), 
    ConfIntUpper0.95=c(cidf_7_9[2], cidf_17_19[2]),
    ConfIntLower0.9=c(cidf_7_9_09[1], cidf_17_19_09[1]), 
    ConfIntUpper0.9=c(cidf_7_9_09[2], cidf_17_19_09[2])
  ) 
  
  return(kable(cidf, caption=title))
}

DDReps <- function(variance, k, d) {
  if (k == 4) h = 3.101;
  if (k == 5) h = 3.258;
  if (k == 3) h = 2.872;
  if (k == 6) h = 3.377;
  
  return(max(c(21, ceiling((h^2 * variance)/d^2))))
}

## PLOT FUNCTIONS
bpOfMeans <- function(datafr, from, to, days_simulated, title, showlegend=T) {
  bplot <- plot_ly(
    type="box",
    legendgroup = "g1",
    width = 1200) %>%
  layout(yaxis = list(title = title),
         showlegend = TRUE,
         legend=list(x = 1, y = 0.9),
         font = list(size = 18),
         xaxis = list(showticklabels = FALSE)
         )

  for (i in 1:length(datafr)) {
    bplot <- add_trace(
    bplot, 
    y=meansFromTo(datafr[[i]], from, to, days_simulated), 
    name = srcFiles[i],
    boxpoints = "all",
    legendgroup = "g1",
    showlegend=showlegend)
  }
  
  return(bplot)
}

```

```{r include=FALSE}
# srcFiles <- c("coordiante_1.csv", "coordiante_3.csv", "coordiante_5.csv", "coordiante_7.csv", "coordiante_9.csv")
# srcFiles <- c("basic_cycling_10.csv", "basic_cycling_15.csv", "basic_cycling_20.csv", "basic_cycling_25.csv", "basic_cycling_30.csv")
# srcFiles <- c("informed_cycling_10.csv", "informed_cycling_15.csv", "informed_cycling_20.csv", "informed_cycling_25.csv", "informed_cycling_30.csv")
# srcFiles <- c("queue_weighted_cycling_10.csv", "queue_weighted_cycling_20.csv", "queue_weighted_cycling_30.csv", "queue_weighted_cycling_40.csv", "queue_weighted_cycling_50.csv")
# srcFiles <- c("flow_weighted_cycling_30.csv", "flow_weighted_cycling_40.csv", "flow_weighted_cycling_50.csv", "flow_weighted_cycling_60.csv", "flow_weighted_cycling_80.csv", "flow_weighted_cycling_100.csv", "flow_weighted_cycling_125.csv")

# srcFiles <- c("tie_basic_iat30_pl25.csv", "tie_informed_iat30_pl25.csv", "tie_dens_iat30_pl30.csv", "tie_queue_iat30_pl30.csv", "tie_flow_iat30_pl30.csv", "tie_wei_iat30_pl30.csv", "tie_coord_iat30_pl30.csv")
# srcFiles <- c("1way_(or_another).csv", "2lane.csv", "3lane.csv", "highway.csv")
# srcFiles <- c("maas_home_basic.csv", "maas_home_informed.csv", "maas_home_density.csv", "maas_home_queue.csv", "maas_home_flow.csv", "maas_home_weighted.csv")
srcFiles <- c("two_districts_basic_30.csv", "1lane.csv", "two_districts_density_weighted_30.csv", "two_districts_queue_30.csv", "two_districts_flow_30.csv", "two_districts_weighted_30.csv", "two_districts_coordinated_30.csv")

## READ IN EXPERIMENTS
data_frames <- list()
i = 1
for (filename in srcFiles) {
  data_frames[[i]] <- read.csv(paste("csv-data/", filename, sep=""), sep = ";");
  i = i + 1
}

for (i in 1:length(data_frames)) {
  data_frames[[i]]$time <- data_frames[[i]]$time/60/60
  data_frames[[i]]$numb_cars[is.na(data_frames[[i]]$numb_cars)] <- 0
  data_frames[[i]]$numb_cars_in[is.na(data_frames[[i]]$numb_cars_in)] <- 0
  data_frames[[i]]$numb_cars_out[is.na(data_frames[[i]]$numb_cars_out)] <- 0
  data_frames[[i]]$avg_velo[is.na(data_frames[[i]]$avg_velo)] <- 0
  data_frames[[i]]$avg_velo_in_traffic[is.na(data_frames[[i]]$avg_velo_in_traffic)] <- 0
  data_frames[[i]]$frac_wait[is.na(data_frames[[i]]$frac_wait)] <- 0
}

## AVERAGING OVER DAYS FOR EACH EXPERIMENT
times <- data_frames[[1]]$time
measurements_per_day <- length(times[times < 24])
days_simulated <- length(times) %/% measurements_per_day

frac_waits <- list()
avg_speeds <- list()
avg_speeds_in <- list()
numb_cars <- list()
numb_cars_in <- list()
numb_cars_out <- list()

for (i_exp in 1:length(data_frames)) {
  data_frames[[i_exp]]$time <- data_frames[[i_exp]]$time %% 24;
  
  frac_waits[[i_exp]] <- data.frame(matrix(ncol=days_simulated + 1, nrow=0))
  colnames(frac_waits[[i_exp]]) <- c("time", paste("D", 1:days_simulated, sep = ""))
  
  avg_speeds[[i_exp]] <- data.frame(matrix(ncol=days_simulated + 1, nrow=0))
  colnames(avg_speeds[[i_exp]]) <- c("time", paste("D", 1:days_simulated, sep = ""))
  
  avg_speeds_in[[i_exp]] <- data.frame(matrix(ncol=days_simulated + 1, nrow=0))
  colnames(avg_speeds_in[[i_exp]]) <- c("time", paste("D", 1:days_simulated, sep = ""))
  
  numb_cars[[i_exp]] <- data.frame(matrix(ncol=days_simulated + 1, nrow=0))
  colnames(numb_cars[[i_exp]]) <- c("time", paste("D", 1:days_simulated, sep = ""))
  
  numb_cars_in[[i_exp]] <- data.frame(matrix(ncol=days_simulated + 1, nrow=0))
  colnames(numb_cars_in[[i_exp]]) <- c("time", paste("D", 1:days_simulated, sep = ""))
  
  numb_cars_out[[i_exp]] <- data.frame(matrix(ncol=days_simulated + 1, nrow=0))
  colnames(numb_cars_out[[i_exp]]) <- c("time", paste("D", 1:days_simulated, sep = ""))
  
  for (i in 1:measurements_per_day) {
    frac_waits[[i_exp]][i,] = c(
      times[i], 
      data_frames[[i_exp]][((0:(days_simulated-1)) * measurements_per_day) + i,]$frac_wait
    )
    
    avg_speeds[[i_exp]][i,] = c(
      times[i], 
      data_frames[[i_exp]][((0:(days_simulated-1)) * measurements_per_day) + i,]$avg_velo
    )
    
    avg_speeds_in[[i_exp]][i,] = c(
      times[i], 
      data_frames[[i_exp]][((0:(days_simulated-1)) * measurements_per_day) + i,]$avg_velo_in_traffic
    )
    
    numb_cars[[i_exp]][i,] = c(
      times[i], 
      data_frames[[i_exp]][((0:(days_simulated-1)) * measurements_per_day) + i,]$numb_cars
    )
    
    numb_cars_in[[i_exp]][i,] = c(
      times[i], 
      data_frames[[i_exp]][((0:(days_simulated-1)) * measurements_per_day) + i,]$numb_cars_in
    )
    
    numb_cars_out[[i_exp]][i,] = c(
      times[i], 
      data_frames[[i_exp]][((0:(days_simulated-1)) * measurements_per_day) + i,]$numb_cars_out
    )
  }
  
  frac_waits[[i_exp]]$mean <- rowMeans(frac_waits[[i_exp]][,3:(days_simulated+1)])
  avg_speeds[[i_exp]]$mean <- rowMeans(avg_speeds[[i_exp]][,3:(days_simulated+1)])
  avg_speeds_in[[i_exp]]$mean <- rowMeans(avg_speeds_in[[i_exp]][,3:(days_simulated+1)])
  numb_cars[[i_exp]]$mean <- rowMeans(numb_cars[[i_exp]][,3:(days_simulated+1)])
  numb_cars_in[[i_exp]]$mean <- rowMeans(numb_cars_in[[i_exp]][,3:(days_simulated+1)])
  numb_cars_out[[i_exp]]$mean <- rowMeans(numb_cars_out[[i_exp]][,3:(days_simulated+1)])
  
  frac_waits[[i_exp]]$var <- rowVars(frac_waits[[i_exp]][,3:(days_simulated+1)])
  avg_speeds[[i_exp]]$var <- rowVars(avg_speeds[[i_exp]][,3:(days_simulated+1)])
  avg_speeds_in[[i_exp]]$var <- rowVars(avg_speeds_in[[i_exp]][,3:(days_simulated+1)])
  numb_cars[[i_exp]]$var <- rowVars(numb_cars[[i_exp]][,3:(days_simulated+1)])
  numb_cars_in[[i_exp]]$var <- rowVars(numb_cars_in[[i_exp]][,3:(days_simulated+1)])
  numb_cars_out[[i_exp]]$var <- rowVars(numb_cars_out[[i_exp]][,3:(days_simulated+1)])
}
```

## DUDEWICZ DALAL

```{r}
DDReps(meansFromTo(avg_speeds_in[[3]], 7, 9, days_simulated), 6, 0.4) - 21
```


## Number of Cars on the Map

```{r echo=FALSE, message=FALSE, results="asis"}
numb_cars_plot <- plot_ly(x=numb_cars[[1]]$time) %>%
  layout(xaxis = list(title = 'Time (h)'),
         yaxis = list(title = 'Number of Cars in System'),
         legend = list(x = 0.80, y = 0.90),
         showlegend = TRUE)

for (i in 1:length(numb_cars)) {
  numb_cars_plot <- add_trace(
    numb_cars_plot, 
    y=fitted(loess(numb_cars[[i]]$mean ~ numb_cars[[i]]$time, span=0.2)), 
    name = srcFiles[i], 
    mode="lines")
}

numb_cars_bplot_morning <- bpOfMeans(numb_cars, 7, 9, days_simulated, "Number of Cars in System between 7am and 9am")
numb_cars_bplot_afternoon <- bpOfMeans(numb_cars, 17, 19, days_simulated, "Number of Cars in System between 17pm and 19pm")

numb_cars_plot
numb_cars_bplot_morning
numb_cars_bplot_afternoon
for (i in 1:length(numb_cars)) {
  print(confIntTable(numb_cars[[i]], paste("Means and Confidence Intervals for", srcFiles[i])))
}
```

## Number of Cars on the Map actually in Traffic

```{r echo=FALSE, message=FALSE, results="asis"}
numb_cars_in_plot <- plot_ly(x=numb_cars_in[[1]]$time) %>%
  layout(xaxis = list(title = 'Time (h)'),
         yaxis = list(title = 'Number of Cars in System'),
         legend = list(x = 0.80, y = 0.90),
         showlegend = TRUE)

for (i in 1:length(numb_cars_in)) {
  numb_cars_in_plot <- add_trace(
    numb_cars_in_plot, 
    y=fitted(loess(numb_cars_in[[i]]$mean ~ numb_cars_in[[i]]$time, span=0.2)), 
    name = srcFiles[i], 
    mode="lines")
}

numb_cars_in_bplot_morning <- bpOfMeans(numb_cars_in, 7, 9, days_simulated, "Number of Cars actually in traffic between 7am and 9am")
numb_cars_in_bplot_afternoon <- bpOfMeans(numb_cars_in, 17, 19, days_simulated, "Number of Cars actually in traffic between 17pm and 19pm")

numb_cars_in_plot
numb_cars_in_bplot_morning
numb_cars_in_bplot_afternoon
for (i in 1:length(numb_cars_in)) {
  print(confIntTable(numb_cars_in[[i]], paste("Means and Confidence Intervals for", srcFiles[i])))
}
```



## Average Velocities

```{r echo=FALSE, message=FALSE, results="asis"}
avg_speeds_plot <- plot_ly(x=avg_speeds[[1]]$time) %>%
  layout(xaxis = list(title = 'Time (h)'),
         yaxis = list(title = 'Average Velocity'),
         legend = list(x = 0.80, y = 0.90),
         showlegend = TRUE)

for (i in 1:length(avg_speeds)) {
  avg_speeds_plot <- add_trace(
    avg_speeds_plot, 
    y=fitted(loess(avg_speeds[[i]]$mean ~ avg_speeds[[i]]$time, span=0.2)), 
    name = srcFiles[i], 
    mode="lines")
}

avg_speeds_bplot_morning <- bpOfMeans(avg_speeds, 7, 9, days_simulated, "Average Velocity between 7 and 9")
avg_speeds_bplot_afternoon <- bpOfMeans(avg_speeds, 17, 19, days_simulated, "Average Velocity between 17 and 19")

avg_speeds_plot
avg_speeds_bplot_morning
avg_speeds_bplot_afternoon
for (i in 1:length(avg_speeds)) {
  print(confIntTable(avg_speeds[[i]], paste("Means and Confidence Intervals for", srcFiles[i])))
}

```

## Average Velocities of In-Traffic Cars

```{r echo=FALSE, message=FALSE, results="asis"}
avg_speeds_in_plot <- plot_ly(x=avg_speeds_in[[1]]$time) %>%
  layout(xaxis = list(title = 'Time (h)'),
         yaxis = list(title = 'Average Velocity'),
         legend = list(x = 0.90, y = 0.90),
         showlegend = TRUE)

for (i in 1:length(avg_speeds_in)) {
  avg_speeds_in_plot <- add_trace(
    avg_speeds_in_plot, 
    y=fitted(loess(avg_speeds_in[[i]]$mean ~ avg_speeds_in[[i]]$time, span=0.2)), 
    name = srcFiles[i], 
    mode="lines")
}

avg_speeds_in_bplot_morning <- bpOfMeans(avg_speeds_in, 7, 9, days_simulated, "Average Velocity between 7 and 9")
avg_speeds_in_bplot_afternoon <- bpOfMeans(avg_speeds_in, 17, 19, days_simulated, "Average Velocity between 17 and 19")

avg_speeds_in_plot
avg_speeds_in_bplot_morning
avg_speeds_in_bplot_afternoon
for (i in 1:length(avg_speeds_in)) {
  print(confIntTable(avg_speeds_in[[i]], paste("Means and Confidence Intervals for", srcFiles[i])))
}

for (i in 3:length(avg_speeds_in)) {
  print(srcFiles[i])
  print(meanDiffConfInt(avg_speeds_in[[1]], avg_speeds_in[[i]], 7, 9, 0.05))
}


```



## Average Percentage of Cars Waiting

```{r echo=FALSE, message=FALSE, results="asis"}
frac_waits_plot <- plot_ly(x=frac_waits[[1]]$time) %>%
  layout(xaxis = list(title = 'Time (h)'),
         yaxis = list(title = 'Average Fractional Waiting Time'),
         legend = list(x = 0.80, y = 0.90),
         showlegend = TRUE)

for (i in 1:length(frac_waits)) {
  frac_waits_plot <- add_trace(
    frac_waits_plot, 
    y=fitted(loess(frac_waits[[i]]$mean ~ frac_waits[[i]]$time, span=0.2)), 
    name = srcFiles[i], 
    mode="lines")
}

frac_waits_bplot_morning <- bpOfMeans(frac_waits, 7, 9, days_simulated, "Average Percentage of Cars waiting between 7 and 9")
frac_waits_bplot_afternoon <- bpOfMeans(frac_waits, 17, 19, days_simulated, "Average Percentage of Cars waiting between 17 and 19")

frac_waits_plot
frac_waits_bplot_morning
frac_waits_bplot_afternoon
for (i in 1:length(frac_waits)) {
  print(confIntTable(frac_waits[[i]], paste("Means and Confidence Intervals for", srcFiles[i])))
}

for (i in 3:length(frac_waits)) {
  print(srcFiles[i])
  print(meanDiffConfInt(frac_waits[[1]], frac_waits[[i]], 7, 9, 0.05))
}

```

